ToDo/WebUI/Controllers/ProjectsController.cs
using AutoMapper;
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;
using Microsoft.AspNet.Identity;
using Domain.Entities;

namespace WebUI.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private IProjectRepository ProjectRepository;

        public ProjectsController(IProjectRepository projectRepository)
        {
            this.ProjectRepository = projectRepository;
        }

        // GET: Project
        public ActionResult Index()
        {
            var projects = ProjectRepository.Projects(User.Identity.GetUserId()).OrderBy(x => x.Name).ToList();
            return View(projects);
        }


        // GET: Project/Create
        [HttpGet]
        public ActionResult Create()
        {
            ProjectViewModel model = new ProjectViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ProjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<Models.ProjectViewModel, Domain.Entities.Project>();
                Domain.Entities.Project domainModel = Mapper.Map<ProjectViewModel, Domain.Entities.Project>(model);
                domainModel.UserID = User.Identity.GetUserId();
                ProjectRepository.CreateProject(domainModel);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Mapper.CreateMap<Domain.Entities.Project, ProjectViewModel>();
            ProjectViewModel model = Mapper.Map<Domain.Entities.Project, ProjectViewModel>(ProjectRepository.GetProject(id, User.Identity.GetUserId()));
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ProjectViewModel model)
        {
            if(ModelState.IsValid)
            {
                Mapper.CreateMap<Models.ProjectViewModel, Domain.Entities.Project>();
                Domain.Entities.Project domainModel = Mapper.Map<ProjectViewModel, Domain.Entities.Project>(model);
                ProjectRepository.UpdateProject(domainModel);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // Get Project/Details/1
        public ActionResult Details(int id)
        {
            var project = ProjectRepository.Projects(User.Identity.GetUserId()).First(x => x.Id == id);
            Mapper.CreateMap<Domain.Entities.Project, ProjectViewModel>();
            ProjectViewModel model = Mapper.Map<Domain.Entities.Project, ProjectViewModel>(project);


            List<ToDo> todos = project.ToDos.OrderBy(x => x.Done).OrderBy(x => x.FinishDate).OrderBy(x => x.Title).ToList();
            Mapper.CreateMap<Domain.Entities.ToDo, ToDoViewModel>()
                .ForMember(dest => dest.Tags, opt => opt.MapFrom(src => String.Join(",", src.Tags.Select(x => x.Name))));
            List<ToDoViewModel> todoViewList = new List<ToDoViewModel>();
            foreach (var t in todos)
            {
                todoViewList.Add(Mapper.Map<Domain.Entities.ToDo, ToDoViewModel>(t));
            }

            ViewBag.ToDos = todoViewList;
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            ProjectRepository.DeleteProject(User.Identity.GetUserId(), id);
            return RedirectToAction("Index");
        }
    }
}

ToDo/WebUI/Controllers/ReportsController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace WebUI.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private IReportRepository ReportRepository;

        public ReportsController(IReportRepository reportRepository)
        {
            this.ReportRepository = reportRepository;
        }

        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ProjectCountPieReport()
        {
            var data = ReportRepository.ProjectCountPieReportData(User.Identity.GetUserId(), null);
            List<string> colors= new List<string>();
            foreach(var r in data)
            {
                if (r == data.First())
                    continue;
                int i=0;
                foreach (var c in r)
                { 
                    if (i == 2)
                        colors.Add((string)c);
                    i++;
                }
            }
            return Json(new { data=data, colors=colors}, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ProjectTimePieReport()
        {
            var data = ReportRepository.ProjectTimePieReportData(User.Identity.GetUserId(), null);
            List<string> colors = new List<string>();
            foreach (var r in data)
            {
                if (r == data.First())
                    continue;
                int i = 0;
                foreach (var c in r)
                {
                    if (i == 2)
                        colors.Add((string)c);
                    i++;
                }
            }
            return Json(new { data = data, colors = colors }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult TagCountPieReport()
        {
            var data = ReportRepository.TagCountPieReportData(User.Identity.GetUserId(), null);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult TagTimePieReport()
        {
            var data = ReportRepository.TagTimePieReportData(User.Identity.GetUserId(), null);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

ToDo/WebUI/Controllers/TagsController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebUI.Models;
using AutoMapper;
using WebUI.AutoMapper;

namespace WebUI.Controllers
{
    [Authorize]
    public class TagsController : Controller
    {
        private ITagsRepository TagsRepository;

        public TagsController(ITagsRepository tagsRepository)
        {
            this.TagsRepository = tagsRepository;
        }

        // GET: Tags
        public ActionResult Index()
        {
            var tags = TagsRepository.Tags(User.Identity.GetUserId()).ToList();
            Mapper.CreateMap<Domain.Entities.Tag, TagViewModel>();
            List<TagViewModel> model = new List<TagViewModel>();
            foreach (var tag in tags)
            {
                var tagViewModel = Mapper.Map<Domain.Entities.Tag, TagViewModel>(tag);
                tagViewModel.ToDoCount = TagsRepository.ToDos(User.Identity.GetUserId(), tagViewModel.Name).Count();
                model.Add(tagViewModel);
            }
            model=model.OrderByDescending(x => x.ToDoCount).ToList();
            return View(model);
        }

        public ActionResult Tag(string name)
        {
            List<ToDo> todos=TagsRepository.ToDos(User.Identity.GetUserId(),name).OrderBy(x=>x.Done).OrderBy(x=>x.FinishDate).OrderBy(x=>x.Title).ToList();
            Mapper.CreateMap<Domain.Entities.ToDo, ToDoViewModel>()
                .ForMember(dest => dest.Tags, opt => opt.MapFrom(src => String.Join(",",src.Tags.Select(x=>x.Name))));
            List<ToDoViewModel> model = new List<ToDoViewModel>();
            foreach(var t in todos)
            {
                model.Add(Mapper.Map<Domain.Entities.ToDo, ToDoViewModel>(t));
            }
            ViewBag.TagName = name;
            return View(model);
        }
    }
}

ToDo/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Resources.FooterText </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" media="screen" href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker.min.css">
    <link href="~/Content/bootstrap-colorselector.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.HomePage, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Zadania", "Index", "Home")</li>*@
                    @*<li>@Html.ActionLink("Statystyki", "Index", "Home")</li>*@
                    <li>@Html.ActionLink(Resources.ToDos, "Day", "ToDos", new { date = "today" }, new { })</li>
                    <li>@Html.ActionLink(Resources.Projects, "Index", "Projects")</li>
                    <li>@Html.ActionLink(Resources.Tags, "Index", "Tags")</li>
                    <li>@Html.ActionLink(Resources.Reports, "Index", "Reports")</li>
                    <li>@Html.ActionLink(Resources.About, "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Resources.FooterText </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment-with-locales.min.js")
    @Scripts.Render("//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js")
    <script src="~/Scripts/bootstrap-select.min.js"></script>
    <script src="~/Scripts/bootstrap-colorselector.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.bootstrap.min.js"></script>
    <script src="~/Scripts/todos.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>