ToDo/WebUI/Models/ToDoViewModels.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Models
{
    public class ToDoViewModels
    {
    }

    public class ToDoViewModel
    {
        [HiddenInput]
        public int Id { get; set; }

        [Display(Name = "Title", ResourceType = typeof(Resources.Resources))]
        [Required(ErrorMessageResourceType = (typeof(Resources.Resources)), ErrorMessageResourceName = "PropertyValueRequired")]
        public string Title { get; set; }

        [Display(Name = "Done", ResourceType = typeof(Resources.Resources))]
        public bool Done { get; set; }

        [Display(Name = "Estimation", ResourceType = typeof(Resources.Resources))]
        public TimeSpan? Estimation { get; set; }

        [Display(Name = "StartDate", ResourceType = typeof(Resources.Resources))]
        [DataType(DataType.Date)]
        [UIHint("Date")]
        public Nullable<DateTime> StartDate { get; set; }

        [Display(Name = "FinishDate", ResourceType = typeof(Resources.Resources))]
        [DataType(DataType.Date)]
        [UIHint("Date")]
        public Nullable<DateTime> FinishDate { get; set; }

        public ApplicationUser User { get; set; }

        [HiddenInput]
        [UIHint("Project")]
        public int? ProjectID { get; set; }

        [Display(Name = "Project", ResourceType = typeof(Resources.Resources))]
        public Project Project { get; set; }

        public ICollection<Note> Notes { get; set; }

        public ICollection<Alert> Alerts { get; set; }

        [Display(Name = "Tags", ResourceType = typeof(Resources.Resources))]
        [RegularExpression("^([^,]+(,[^,]+)*)?$", ErrorMessageResourceType = (typeof(Resources.Resources)), ErrorMessageResourceName = "InvalidTagFormat")]
        public string Tags { get; set; }
    }

    public class DashBoardModelView
    {
    
    }


    //public class ToDoListViewModel
    //{
    //    public IEnumerable<ToDo> All { get; set; }

    //    public ToDo New { get; set; }
    //}
}

ToDo/WebUI/Controllers/AlertsController.cs
using AutoMapper;
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize]
    public class AlertsController : Controller
    {
        private IAlertRepository AlertRepository;

        public AlertsController(IAlertRepository alertRepository)
        {
            this.AlertRepository = alertRepository;
        }

        // GET: Alert
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create(int toDoId)
        {
            AlertViewModel model = new AlertViewModel();
            model.ToDoID = toDoId;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(AlertViewModel model)
        {
            if(ModelState.IsValid)
            {
                Mapper.CreateMap<AlertViewModel, Domain.Entities.Alert>();
                Domain.Entities.Alert domainModel = Mapper.Map<AlertViewModel, Domain.Entities.Alert>(model);
                AlertRepository.CreateAlert(domainModel);
                return RedirectToAction("Details", "ToDos", new { id = model.ToDoID });
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Mapper.CreateMap<Domain.Entities.Alert, AlertViewModel>();
            AlertViewModel model = Mapper.Map<Domain.Entities.Alert, AlertViewModel>(AlertRepository.GetAlert(id));
            model.Date = model.Date.ToLocalTime();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AlertViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<Models.AlertViewModel, Domain.Entities.Alert>();
                Domain.Entities.Alert domainModel = Mapper.Map<AlertViewModel, Domain.Entities.Alert>(model);
                AlertRepository.UpdateAlert(domainModel);
                return RedirectToAction("Details", "ToDos", new { id = model.ToDoID });
            }
            return View(model);
        }

        public ActionResult Delete(int toDoId, int id)
        {
            AlertRepository.DeleteAlert(id);
            return RedirectToAction("Details", "ToDos", new { id = toDoId });
        }
    }
}

ToDo/WebUI/Controllers/NotesController.cs
using AutoMapper;
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        INoteRepository NoteRepository;
        IToDoRepository ToDoReposiotry;

        public NotesController(INoteRepository noteRepository, IToDoRepository toDoReposiotry)
        {
            this.NoteRepository = noteRepository;
            this.ToDoReposiotry = toDoReposiotry;
        }

        public ActionResult Create(int toDoId)
        {
            var model = new NoteViewModel();
            model.ToDoID = toDoId;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(NoteViewModel model)
        {
            if(ModelState.IsValid)
            {
                Mapper.CreateMap<Models.NoteViewModel, Domain.Entities.Note>();
                Domain.Entities.Note domainModel = Mapper.Map<NoteViewModel, Domain.Entities.Note>(model);
                NoteRepository.CreateNote(domainModel);
                return RedirectToAction("Details", "ToDos", new { id = model.ToDoID });
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            Mapper.CreateMap<Domain.Entities.Note, NoteViewModel>();
            NoteViewModel model = Mapper.Map<Domain.Entities.Note, NoteViewModel>(NoteRepository.GetNote(id));
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(NoteViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<Models.NoteViewModel, Domain.Entities.Note>();
                Domain.Entities.Note domainModel = Mapper.Map<NoteViewModel, Domain.Entities.Note>(model);
                NoteRepository.UpdateNote(domainModel);
                return RedirectToAction("Details", "ToDos", new { id = model.ToDoID });
            }
            return View(model);
        }

        public ActionResult Delete(int toDoId,int id)
        {
            NoteRepository.DeleteNote(id);
            return RedirectToAction("Details", "ToDos", new { id = toDoId });
        }
    }
}

ToDo/WebUI/Controllers/ToDosController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebUI.Models;
using AutoMapper;
using WebUI.AutoMapper;
using System.Globalization;
using System.Net;
using System.Data.Entity;

namespace WebUI.Controllers
{
    [Authorize]
    public class ToDosController : Controller
    {
        private IToDoRepository ToDoRepository;
        private IProjectRepository ProjectRepository;
        private const string TODAY = "Today";
        private const string TOMORROW = "Tomorrow";

        public ToDosController(IToDoRepository toDoRepository, IProjectRepository projectRepository)
        {
            this.ToDoRepository = toDoRepository;
            this.ProjectRepository = projectRepository;
        }

        // GET: ToDos
        public ActionResult Index()
        {
            ViewBag.Header = Resources.Resources.TodaysTodos;


            IQueryable<ToDo> all = ToDoRepository.ToDos(User.Identity.GetUserId());
            ViewBag.Today = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == DateTime.Today
                ).ToList();

            var tomorrow = DateTime.Today.Date.AddDays(1);
            ViewBag.Tomorrow = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == tomorrow
                ).ToList();
            var nextWeek = DateTime.Today.Date.AddDays(7);
            ViewBag.Week = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) <= nextWeek && DbFunctions.TruncateTime(x.FinishDate.Value) >= DateTime.Today
                ).ToList();

            ViewBag.NoDate = all.Where(
                    x => !x.FinishDate.HasValue
                ).ToList();

            ViewBag.Projects = ProjectRepository.Projects(User.Identity.GetUserId());
            return View();
        }

        public ActionResult Archive()
        {
            IQueryable<ToDo> all = ToDoRepository.ToDos(User.Identity.GetUserId());
            List<ToDo> model = all.Where(x => x.Done).OrderByDescending(x => x.FinishDate).OrderByDescending(x => x.StartDate).ToList();
            return View(model);
        }

        public PartialViewResult DashBoard()
        {
            IQueryable<ToDo> all = ToDoRepository.ToDos(User.Identity.GetUserId());
            ViewBag.Today = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == DateTime.Today
                ).ToList();

            var tomorrow = DateTime.Today.Date.AddDays(1);
            ViewBag.Tomorrow = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == tomorrow
                ).ToList();
            var nextWeek = DateTime.Today.Date.AddDays(7);
            ViewBag.Week = all.Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) <= nextWeek && DbFunctions.TruncateTime(x.FinishDate.Value) >= DateTime.Today
                ).ToList();

            ViewBag.NoDate = all.Where(
                    x => !x.FinishDate.HasValue
                ).ToList();

            ViewBag.Projects = ProjectRepository.Projects(User.Identity.GetUserId());
            return PartialView("_DashBoard");
        }

        // GET: ToDos/Day
        public ActionResult Day(string date)
        {
            IEnumerable<ToDo> model;
            if (String.Equals(date, TODAY, StringComparison.OrdinalIgnoreCase))
            {
                model = ToDoRepository.ToDos(User.Identity.GetUserId()).Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == DateTime.Today
                );
                ViewBag.Date = DateTime.Today.ToShortDateString();
            }
            else if (String.Equals(date, TOMORROW, StringComparison.OrdinalIgnoreCase))
            {
                DateTime dayTomorrow = DateTime.Today.AddDays(1);
                model = ToDoRepository.ToDos(User.Identity.GetUserId()).Where(
                    x => x.FinishDate.HasValue &&
                    DbFunctions.TruncateTime(x.FinishDate.Value) == dayTomorrow
                );
                ViewBag.Date = dayTomorrow.ToShortDateString();
            }
            else
            {
                try
                {
                    DateTime filterDateDay = DateTime.Parse(date,CultureInfo.CurrentCulture.DateTimeFormat);
                    model = ToDoRepository.ToDos(User.Identity.GetUserId()).Where(
                       x => x.FinishDate.HasValue &&
                       DbFunctions.TruncateTime(x.FinishDate.Value) == filterDateDay
                    );
                    ViewBag.Date = filterDateDay.ToShortDateString();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Bad Request");
                }
            }
            ViewBag.Projects = ProjectRepository.Projects(User.Identity.GetUserId());
            return View(model.ToList());
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Title,Estimation,StartDate,FinishDate,ProjectID,Tags")] ToDoViewModel model)
        {
            if (Request.IsAjaxRequest())
            {
                if (ModelState.IsValid)
                {
                    Mapper.CreateMap<Models.ToDoViewModel, Domain.Entities.ToDo>()
                        .ForMember(dest => dest.ProjectID, opt => opt.MapFrom(src => (src.ProjectID.HasValue && src.ProjectID.Value > 0) ? src.ProjectID : null))
                        .ForMember(dest => dest.Tags, opt => opt.ResolveUsing<ToDoTagResolver>());
                    Domain.Entities.ToDo domainModel = Mapper.Map<ToDoViewModel, Domain.Entities.ToDo>(model);
                    ToDoRepository.Create(domainModel, User.Identity.GetUserId());
                    return Json(new { success = true, message = String.Format(Resources.Resources.ToDoCreatedMessage, model.Title) });
                }
                else
                {
                    var modelStateErrors = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors);
                    var validationMessage = Resources.Resources.CreateTodoError + Environment.NewLine;

                    foreach (var modelStateError in modelStateErrors)
                    {
                        validationMessage += modelStateError.ErrorMessage + Environment.NewLine;
                    }
                    return Json(new { success = false, message = validationMessage });
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            Mapper.CreateMap<Domain.Entities.ToDo, ToDoViewModel>();
            ToDoViewModel model = Mapper.Map<Domain.Entities.ToDo, ToDoViewModel>(ToDoRepository.GetToDo(id, User.Identity.GetUserId()));

            model.Alerts = model.Alerts.OrderBy(x => x.Date).ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Mapper.CreateMap<Domain.Entities.ToDo, ToDoViewModel>()
                 .ForMember(dest => dest.Tags, opt => opt.MapFrom(src => String.Join(",", src.Tags.Select(x => x.Name))));
            ToDoViewModel model = Mapper.Map<Domain.Entities.ToDo, ToDoViewModel>(ToDoRepository.GetToDo(id, User.Identity.GetUserId()));
            ViewBag.Projects = ProjectRepository.Projects(User.Identity.GetUserId());
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ToDoViewModel model)
        {
            if (ModelState.IsValid)
            {

                Mapper.CreateMap<Models.ToDoViewModel, Domain.Entities.ToDo>()
                    .ForMember(dest => dest.ProjectID, opt => opt.MapFrom(src => (src.ProjectID.HasValue && src.ProjectID.Value > 0) ? src.ProjectID : null))
                    .ForMember(dest => dest.Tags, opt => opt.ResolveUsing<ToDoTagResolver>());
                Domain.Entities.ToDo domainModel = Mapper.Map<ToDoViewModel, Domain.Entities.ToDo>(model);
                ToDoRepository.Update(domainModel, User.Identity.GetUserId());
                return RedirectToAction("Details", "ToDos", new { id = model.Id });
            }
            ViewBag.Projects = ProjectRepository.Projects(User.Identity.GetUserId());
            return View(model);
        }

        [HttpPost]
        public ActionResult Mark(int Id, bool done)
        {
            var todo = ToDoRepository.ToDos(User.Identity.GetUserId()).First(x => x.Id == Id);
            todo.Done = done;
            ToDoRepository.Update(todo, User.Identity.GetUserId());
            return Json(new { success = true });
        }
    }
}

ToDo/WebUI/Views/ToDos/Day.cshtml
@model IEnumerable<Domain.Entities.ToDo>
@{
    ViewBag.Title = "Day";
}
<br />
<div id="todo-lists-container">
    <table>
        <tr>
            <td class="h2">@Resources.FinishingOn</td>
            <td>
                <div class="input-group date datepicker" id="SelectDayContainer" data-url="@Url.Action("Index")">
                    <input class="form-control " id="Day" name="Day" type="text" value="@ViewBag.Date">
                    <span class="input-group-addon">
                        <span class="glyphicon-calendar glyphicon"></span>
                    </span>
                </div>
            </td>
        </tr>
    </table>
    @Html.Partial("_ToDoList", Model)
</div>

ToDo/WebUI/Views/ToDos/Details.cshtml
@model WebUI.Models.ToDoViewModel

<h3>@Resources.Details <small>@Html.ActionLink(Resources.Edit, "Edit", new { id = Model.Id }) | @Html.ActionLink(Resources.BackToToDoList, "Index")</small></h3>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>

        @if(Model.Project!=null)
        { 
            <dd style="color:@Model.Project.Color">
                @Html.DisplayFor(model => model.Project.Name)
            </dd>
        }
        else
        {
            <dd>
               <text>-</text>
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Estimation)
        </dt>

        <dd>
            @if (Model.Estimation.HasValue)
            {
                <text>@Model.Estimation.Value.ToString(@"hh\:mm")</text>
            }
            else
            {
                <text>-</text>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>

    </dl>
    <h3>@Resources.Notes <a href="@Url.Action("Create", "Notes", new { todoId = Model.Id })"><span class="glyphicon glyphicon-plus"></span></a></h3>
    @foreach (var note in Model.Notes)
    {
        <hr />
        <h4>
            @note.Title
            <a href="@Url.Action("Edit", "Notes", new { todoId = Model.Id, id = note.Id })"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="@Url.Action("Delete", "Notes", new { todoId = Model.Id, id = note.Id })"><span class="glyphicon glyphicon-remove"></span></a>
            <small>@note.Created.ToLocalTime()</small>
        </h4>
        <p>@note.Text</p>
    }
    @if (Model.Notes.Count() == 0)
    {
        <div class="alert alert-info">@Resources.NoNotesMessage</div>
    }
    <h3>@Resources.Alerts <a href="@Url.Action("Create", "Alerts", new { todoId = Model.Id })"><span class="glyphicon glyphicon-plus"></span></a></h3>
    @foreach (var alert in Model.Alerts)
    {
        <hr />
        <div>
            @alert.Date.ToLocalTime()
            <a href="@Url.Action("Edit", "Alerts", new { todoId = Model.Id, id = alert.Id })"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="@Url.Action("Delete", "Alerts", new { todoId = Model.Id, id = alert.Id })"><span class="glyphicon glyphicon-remove"></span></a>
        </div>
    }
    @if (Model.Alerts.Count() == 0)
    {
        <div class="alert alert-info">@Resources.NoAlertsMessage</div>
    }
</div>

ToDo/WebUI/Views/ToDos/Edit.cshtml
@model WebUI.Models.ToDoViewModel


<h2>@Resources.EditToDo <small>@Html.ActionLink(Resources.BackToToDoList, "Index")</small></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Done, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Done)
                    @Html.ValidationMessageFor(model => model.Done, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class='input-group col-md-3'>
                @Html.EditorFor(model => model.ProjectID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estimation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Estimation, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.FinishDate, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.FinishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ToDo/WebUI/Views/ToDos/_ToDoList.cshtml
@model IEnumerable<Domain.Entities.ToDo>

@{
    var projects = Model.Where(x=>x.Project!=null).Select(x => x.Project).Distinct().ToList();
}

@foreach (var p in projects)
{
    var timesum = TimeSpan.FromMilliseconds(Model.Where(x => x.Project == p && x.Estimation.HasValue).Sum(x => x.Estimation.Value.TotalMilliseconds));
    double share = p.DailyTime.HasValue ? timesum.TotalMilliseconds / p.DailyTime.Value.TotalMilliseconds : 0;

    <hr />
    <div class="h3" style="color:@p.Color">
        @p.Name
    </div>
    <strong>
        @Resources.DailyTimeAllocated:
    @if (p.DailyTime.HasValue)
    { <text> @p.DailyTime.Value.ToString(@"h\:mm") </text>}
    else
    { <text> @Resources.NotApplicable </text>}
</strong><br />
    if (!p.DailyTime.HasValue)
    {
        <text><span class="text-info"><strong>@Resources.AllToDosTime @timesum.ToString(@"h\:mm")</strong></span></text>
    }
    else if (share < 0.8)
    {
        <text><span class="text-success"><strong>@Resources.AllToDosTime @timesum.ToString(@"h\:mm") (@string.Format("{0:0.0%}", share))</strong></span></text>
    }
    else if (share < 1)
    {
        <text><span class="text-warning"><strong>@Resources.AllToDosTime @timesum.ToString(@"h\:mm") (@string.Format("{0:0.0%}", share))</strong></span></text>
    }
    else
    {
        <text><span class="text-danger"><strong>@Resources.AllToDosTime @timesum.ToString(@"h\:mm") (@string.Format("{0:0.0%}", share))</strong></span></text>
    }
    <table class="col-md-12">
        <tr>
            <th class="col-md-1"></th>
            <th class="col-md-6">@Resources.Name</th>
            <th class="col-md-4 text-center">@Resources.Estimation</th>
            <th class="col-md-1"></th>
        </tr>
        @foreach (var todo in Model.Where(x => x.Project == p))
        {
            <tr>
                <td>@Html.CheckBoxFor(m => todo.Done, new { @value = todo.Id, @class = "todo-checkbox", @data_url = Url.Action("Mark", "ToDos") }) </td>
                <td>@Html.ActionLink(todo.Title, "Details", new { id = todo.Id })</td>
                <td class="text-center">
                    @Html.DisplayFor(x => todo.Estimation)
                </td>
                <td>
                    <a href="@Url.Action("Create", "Alerts", new { todoId = todo.Id })"><span class="glyphicon glyphicon-bell" title="@Resources.AddAlert"></span></a>
                    <a href="@Url.Action("Create", "Notes", new { todoId = todo.Id })"><span class="glyphicon glyphicon-list" title="@Resources.AddNote"></span></a>
                </td>
            </tr>
        }
    </table>
}

@if (Model.Any(x => x.Project == null))
{ 
    <hr />
    <div class="h3">
        @Resources.NotAssignedToProject
    </div>
    
    var restTimesum = TimeSpan.FromMilliseconds(Model.Where(x => x.Project == null && x.Estimation.HasValue).Sum(x => x.Estimation.Value.TotalMilliseconds));

    <span class="text-info"><strong>@Resources.AllToDosTime @restTimesum.ToString(@"h\:mm")</strong></span>
       
    <table class="col-md-12">
        <tr>
            <th class="col-md-1"></th>
            <th class="col-md-6">@Resources.Name</th>
            <th class="col-md-4 text-center">@Resources.Estimation</th>
            <th class="col-md-1"></th>
        </tr>
        @foreach (var todo in Model.Where(x => x.Project == null))
        {
            <tr>
                <td>@Html.CheckBoxFor(m => todo.Done, new { @value = todo.Id, @class = "todo-checkbox", @data_url = Url.Action("Mark", "ToDos") }) </td>
                <td>@Html.ActionLink(todo.Title, "Details", new { id = todo.Id })</td>
                <td class="text-center">
                    @Html.DisplayFor(x => todo.Estimation)
                </td>
                <td>
                    <a href="@Url.Action("Create", "Alerts", new { todoId = todo.Id })"><span class="glyphicon glyphicon-bell" title="@Resources.AddAlert"></span></a>
                    <a href="@Url.Action("Create", "Notes", new { todoId = todo.Id })"><span class="glyphicon glyphicon-list" title="@Resources.AddNote"></span></a>
                </td>
            </tr>
        }
    </table>
}

@if (!Model.Any())
{
    <hr />
    <div class="alert alert-info"><i class="glyphicon glyphicon-info-sign"></i>@Resources.NoToDosMessage</div>
}